name: actions_practice
on: push
jobs:
  job_1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Node commands
        run: |
          npm init -y
          node app.js
